spring:
  datasource:
    # 각자 PC에 만들어둔 DB 이름을 3306/( )?에 넣어 사용
    url: ${DB_URL}
    # mysql에 생성한 사용자 계정 정보 사용
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: localhost
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      enabled: true             # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B   # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0MB)
#      location: /users/         # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 5MB        # 1개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 5MB     # 1개 요청의 최대 사이즈 (default: 10MB)
logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret-key: ${JWT_SECRET_KEY}

cloud:
  aws:
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET}

server:
  error:
    include-binding-errors: always
    include-message: always
