spring:
  datasource:
    # 각자 PC에 만들어둔 DB 이름을 3306/( )?에 넣어 사용
    url: ${DB_URL}
    # mysql에 생성한 사용자 계정 정보 사용
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secretKey: ${JWT_SECRET_KEY}